[package]
name = "radio"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
http = "1.3.1"
indicatif = "0.18.4"
oauth2 = { version = "5.0.0", features = ["reqwest-blocking", "timing-resistant-secret-traits"] }
reqwest = { version = "0.13.3", features = ["blocking", "json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140", features = ["std"] }
serde_urlencoded = "0.7.1"
thiserror = "2.0.18"
toml = "0.8.22"
ureq = "3.3.0"
url = "2.5.4"
xdg = "2.5.2"

[dev-dependencies]
expect = { git = "https://github.com/gcapizzi/expect.git" }
